version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana-eptelem
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - ./provisioning/:/etc/grafana/provisioning/

  influxdb:
    image: influxdb:1.8
    container_name: influxdb-eptelem
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring

    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Welcome1 


networks:
  monitoring:
volumes:
  grafana-volume:

  influxdb-volume:
